blank_issues_enabled: false
contact_links:
  - name: ğŸ’¬ Preguntas
    url: https://github.com/nubemsystemsdev/[NOMBRE_PROYECTO]/discussions
    about: Usa Discussions para preguntas generales
  - name: ğŸ“š DocumentaciÃ³n
    url: https://github.com/nubemsystemsdev/[NOMBRE_PROYECTO]/tree/main/docs
    about: Revisa la documentaciÃ³n primero
